name: Deploy to saquib-alam-md

on:
  push:
    branches: [ "main" ]
    
env:
  VITE_BASE_API       : https://get-published-nf5wy45qga-uc.a.run.app
  VITE_TITLE          : Zust AI - Dreamlike product photos
  VITE_DESCRIPTION    : Generate stunning product photos using AI
  VITE_KEYWORDS       : Product photography, AI, deep learning, stable diffusion
  VITE_APP_NAME       : home
  mode                : development
  VITE_ENV            : production

jobs:
  deploy_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install yarn@latest -g

      - name: Install Firebase Tools
        run: npm install firebase-tools -g
        
      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run deploy
        run: firebase deploy --project saquib-alam-md --only hosting:saquib-alam-md --token ${{secrets.FIREBASE_TOKEN}} 