name: Deploy to Stage

on:
  push:
    branches: [ "main" ]
    
env:
  VITE_BASE_API       : https://stage-zust-ai-be-5ipjkdoeba-uc.a.run.app
  VITE_TITLE          : Zust AI - Dreamlike product photos
  VITE_DESCRIPTION    : Generate stunning product photos using AI
  VITE_KEYWORDS       : Product photography, AI, deep learning, stable diffusion
  VITE_APP_NAME       : zust
  mode                : development
  VITE_ENV            : production
  VITE_SUPABASE_URL   : https://bptbjokqupygylkbmspj.supabase.co
  VITE_SUPABASE_KEY   : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdGJqb2txdXB5Z3lsa2Jtc3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTAyMjMyMjQsImV4cCI6MjAwNTc5OTIyNH0.jsYmzxC2cLAchXYJbyChACFjQx_rn4IsGfpJUjxTR2w

jobs:
  deploy_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install yarn@latest -g

      - name: Install Firebase Tools
        run: npm install firebase-tools -g
        
      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run deploy
        run: firebase deploy --project saquib-alam-md --only hosting:saquib-alam-md --token ${{secrets.FIREBASE_TOKEN}} 